version: '3.8'
services:
  communication_management:
    build:
      context: ./  # Path to the frontend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose port 3000 from the container to port 3000 on the host
    depends_on:
      - communication_backend  # Ensure backend starts before frontend

  communication_backend:
    build:
      context: ./communication_backend  # Path to the backend directory
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Expose port 3001 from the container to port 3001 on the host
   
    environment:
      MONGO_URI: "mongodb+srv://ranthilini:itp12345678@communication.k8fbczh.mongodb.net/Communication_db?retryWrites=true&w=majority&appName=Communication"  # Ensure this is formatted correctly

    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

